//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HopDong: IValidatableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
        [Required(ErrorMessage ="Không được bỏ trống")]
        public string MaHopDong { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]

        public string LoaiHopDong { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]

        public System.DateTime NgayBatDau { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]

        public System.DateTime NgayKetThuc { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (NgayBatDau > NgayKetThuc)
            {
                yield return new ValidationResult("Ngày Kết Thúc Phải Lớn Hơn Ngày Bắt Đầu");
            }
        }
    }
}
